modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "nuit"
version = "${version}"
displayName = "Nuit"
authors = "AMereBagatelle, FlashyReese"
description = '''
Adds custom skybox support to Minecraft
'''
logoFile = "assets/nuit/nuit_logo.png"

[[dependencies.nuit]]
modId = "neoforge"
type = "required"
versionRange = "[20.6.116,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nuit]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.2,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "nuit-common.mixins.json"
