name: Release CI

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
      - name: Upload assets to releases
        run: ./gradlew build
      - name: Publish to Modrinth, CurseForge & GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: YBz7DOs8
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 408209
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          version-type: release

          loaders: fabric

          version-resolver: latest